language: cpp

script:
  - cd project5/src && make && cd -
  - cd project4/src && make && cd -
  - cd project3/src && make && cd - 
    
before_install:
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install openmpi-bin
    ## Armadillo C++
  - sudo apt-get install -qq libblas-dev liblapack-dev libopenblas-dev
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-5.100.2.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
  - make --quiet -j 4
  - sudo make --quiet install
  ### Fixes issues with IWYU (suggesting for example <armadillo_bits/Base_bones.hpp> instead of <armadillo>)
  ### Using the *literal style* for this line, as it collides with YAML
  - |-
    sudo find /usr/local/include/armadillo_bits -name *.hpp -exec sed -i -e '1i\/\/ IWYU pragma\: private\, include \<armadillo\>' {} \;
  - cd ..
  - rm -Rf armadillo armadillo.tar.gz
  # - sudo apt-get update && sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra dvipng
  # - wget http://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz/download --output-document biber-linux_x86_32.tar.gz
  # - tar -xvzf biber-linux_x86_32.tar.gz
  # - sudo mv biber /usr/bin/
  # - sudo apt-get install python-pip
  # - sudo pip install matplotlib
  

notifications:
  email: false
